---
title: "Data Tidying"
author: "Mike Loranty"
date: "1/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = F, message = F}
library(dplyr)
library(tidyr)
```

To call a function from a specific package type 'package_name::function_name()'

# Data Tidying

Read in the data file

```{r}
catch_df <- read.csv(file = "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1",
                  stringsAsFactors = FALSE)

# for Windows there could be a problem, if so, use the following
#read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", 
#               method = "libcurl"),stringsAsFactors = FALSE)

head(catch_df)
```

cmd + shift + m is the keyboard shortcut for the pipe operator %>%

This section will make the catch data frame tidy

*  Remove marginal sum and notes column 
*  Move from wide to long format 

```{r}
catch_long <- catch_df %>%
  select(-All, -notesRegCode) %>% 
  # in gather you need to specify columns - this can be positive or negative
  gather(key = "species", value = "catch", -Year, -Region)

head(catch_long)
```



```{r}
catch_cleaned <- catch_long %>% 
  rename(catch_thousands = catch) #%>% 
 # mutate(catch = catch_thousands*1000)

```


```{r}
test_catch <- as.integer(catch_cleaned$catch_thousands)

i <- which(is.na(test_catch)==T)

catch_cleaned[i,]
```

# Split-Apply-Combine

# Joins
