---
title: "Reading netcdf files"
author: "Mike Loranty"
date: "1/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ncdf4)
library(dplyr)
library(tidyr)
library(ggplot2)
```

Open a netcdf file
```{r}
nc <- nc_open("data/WG2013CTD.nc")
#print(nc) to view vars in the file
```


Get a vector of the names of variables in the file
```{r}
var <- attributes(nc$var)$names
var
```

Get the dimensions
```{r}
dims <- attributes(nc$dim)$names
dims
```


Get salininty, time, and depth data from the file
```{r}
salinity <- ncvar_get(nc, "sal")
time <- ncvar_get(nc, "time")
depth <- ncvar_get(nc, "z")
```

# Reformat the outputs

First reformat the time
```{r}
time <- as.POSIXct((time + 719529)*86400, origin = "1970-01-01", tz = "UTC")
```

Coerce the salnity data into a data frame
```{r}
salinity_data <- as.data.frame(salinity)
```

Assign column names to depth values
```{r}
names(salinity_data) <- as.character(depth)
```

Reshape and add time
```{r}
salinity_long <- salinity_data %>% 
  mutate(time = time) %>% 
  gather(key = "depth", value = "salinity", -time) %>% 
  mutate(depth = as.numeric(depth))
```


# Plots

```{r}
ggplot(salinity_long, mapping = aes(x = time, y = depth, fill = salinity)) +
  geom_raster()
```

```{r}
ggplot(salinity_long, mapping = aes(x = salinity, y = depth, color = time)) +
  geom_line() +
  scale_y_reverse()
```

